/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.User;

import MODEL.ChiTietDonHang;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author tsmda
 */
public class cardChiTietDonHang extends javax.swing.JPanel {

    ChiTietDonHang ct = new ChiTietDonHang();

    public cardChiTietDonHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenSP = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblMaDH = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setPreferredSize(new java.awt.Dimension(1100, 180));

        lblTenSP.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTenSP.setText("Tên sản phẩm");

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSize.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblSize.setText("size");

        lblGia.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblGia.setText("giá");

        lblThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblThanhTien.setText("Thành tiền");

        lblSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblSoLuong.setText("số lượng");

        lblMaDH.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblMaDH.setText("MaDH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaDH;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThanhTien;
    // End of variables declaration//GEN-END:variables

    public void show1ChiTietDonHang() {

        lblMaDH.setText("" + ct.getMaDonHang());
        lblTenSP.setText(ct.getTenSanPham());
        lblSize.setText(ct.getKichThuoc());
        lblGia.setText("" + ct.getGia() + " $");
        lblSoLuong.setText("" + ct.getSoLuong());
        lblThanhTien.setText("" + ct.getThanhTien() + " $");
        ImageIcon icon = new ImageIcon("src\\IMG_Product\\IMG_Product1\\" + ct.getAnh());
        Image scaledImage = icon.getImage().getScaledInstance(90, 120, Image.SCALE_SMOOTH);
        icon.setImage(scaledImage);
        lblHinh.setIcon(icon);

    }
}
