/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.DonHangDao;
import MODEL.DonHang;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranh
 */
public class frmDonHang extends javax.swing.JInternalFrame {

    List<DonHang> listDH = new ArrayList<>();
    DonHangDao dhDao = new DonHangDao();
    DonHang dh = new DonHang();

    int index = 0;
    DefaultTableModel tblModel = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    frmCTDH fadd = new frmCTDH();

    public frmDonHang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        btnHuydh = new javax.swing.JButton();
        btnsuadonhang = new javax.swing.JButton();
        btnChiTiet1 = new javax.swing.JButton();
        txtMadonhang = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        lblTongSL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonhang = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1650, 855));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1622, 135));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Trạng thái đơn hàng:");

        cboTrangThai.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang xử lý", "Đang giao", "Đã giao", "Hoàn tất" }));
        cboTrangThai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnHuydh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btnHuydh.setText("Hủy đơn hàng");
        btnHuydh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuydh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuydhActionPerformed(evt);
            }
        });

        btnsuadonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnsuadonhang.setText("Sửa đơn hàng");
        btnsuadonhang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuadonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuadonhangActionPerformed(evt);
            }
        });

        btnChiTiet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chitiet.png"))); // NOI18N
        btnChiTiet1.setText("Chi tiết đơn hàng");
        btnChiTiet1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiTiet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTiet1ActionPerformed(evt);
            }
        });

        txtMadonhang.setEditable(false);
        txtMadonhang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtMadonhang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)), "Mã loại sản phẩm", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset.setActionCommand("  Xóa");
        btnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setName(""); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTongSL.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTongSL.setForeground(new java.awt.Color(204, 0, 0));
        lblTongSL.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtMadonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsuadonhang)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHuydh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChiTiet1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(lblTongSL)
                .addGap(48, 48, 48)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMadonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHuydh)
                            .addComponent(btnChiTiet1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuadonhang))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblDonhang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblDonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn hàng", "Tên đăng nhập", "Ngày đặt", "Email", "Họ tên", "Số điện thoại", "Chi tiết địa chỉ", "Tổng giá trị", "Hình thức thanh toán", "Trạng thái"
            }
        ));
        tblDonhang.setRowHeight(50);
        tblDonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDonhang);
        if (tblDonhang.getColumnModel().getColumnCount() > 0) {
            tblDonhang.getColumnModel().getColumn(0).setMinWidth(70);
            tblDonhang.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblDonhang.getColumnModel().getColumn(0).setMaxWidth(70);
            tblDonhang.getColumnModel().getColumn(1).setMinWidth(130);
            tblDonhang.getColumnModel().getColumn(1).setPreferredWidth(130);
            tblDonhang.getColumnModel().getColumn(1).setMaxWidth(130);
            tblDonhang.getColumnModel().getColumn(2).setMinWidth(220);
            tblDonhang.getColumnModel().getColumn(2).setPreferredWidth(220);
            tblDonhang.getColumnModel().getColumn(2).setMaxWidth(220);
            tblDonhang.getColumnModel().getColumn(3).setMinWidth(250);
            tblDonhang.getColumnModel().getColumn(3).setPreferredWidth(250);
            tblDonhang.getColumnModel().getColumn(3).setMaxWidth(250);
            tblDonhang.getColumnModel().getColumn(4).setMinWidth(150);
            tblDonhang.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblDonhang.getColumnModel().getColumn(4).setMaxWidth(150);
            tblDonhang.getColumnModel().getColumn(5).setMinWidth(130);
            tblDonhang.getColumnModel().getColumn(5).setPreferredWidth(130);
            tblDonhang.getColumnModel().getColumn(5).setMaxWidth(130);
            tblDonhang.getColumnModel().getColumn(7).setMinWidth(100);
            tblDonhang.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblDonhang.getColumnModel().getColumn(7).setMaxWidth(100);
            tblDonhang.getColumnModel().getColumn(9).setMinWidth(130);
            tblDonhang.getColumnModel().getColumn(9).setPreferredWidth(130);
            tblDonhang.getColumnModel().getColumn(9).setMaxWidth(130);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuydhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuydhActionPerformed
        deleteDH();
    }//GEN-LAST:event_btnHuydhActionPerformed

    private void btnsuadonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuadonhangActionPerformed
        updateDH();
    }//GEN-LAST:event_btnsuadonhangActionPerformed

    private void btnChiTiet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTiet1ActionPerformed
        showCTDH();
    }//GEN-LAST:event_btnChiTiet1ActionPerformed

    private void tblDonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonhangMouseClicked
        showDetail();
    }//GEN-LAST:event_tblDonhangMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        fillToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet1;
    private javax.swing.JButton btnHuydh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnsuadonhang;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTongSL;
    private javax.swing.JTable tblDonhang;
    private javax.swing.JTextField txtMadonhang;
    // End of variables declaration//GEN-END:variables

    public void fillToTable() {

        listDH = dhDao.showAllDonHang();

        tblModel = (DefaultTableModel) tblDonhang.getModel();
        tblModel.setRowCount(0);
        for (DonHang dh : listDH) {
            Object[] row = new Object[]{dh.getMaDonHang(), dh.getTenDN(), dh.getNgayDat(), dh.getEmail(), dh.getHoTen(), dh.getSoDienThoai(), dh.getChiTietDiaChi(), dh.getTongGiaTri(), dh.getHinhThucThanhToan(), dh.getTrangThai()};
            tblModel.addRow(row);
        }
        tblDonhang.setModel(tblModel);
        tongSL();
    }

    public void deleteDH() {
        DonHangDao dhDao = new DonHangDao();
        index = tblDonhang.getSelectedRow();
        DonHang dh = listDH.get(index);

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon don hang muon Huy");

        } else {
            if (dhDao.huyDonHang("" + dh.getMaDonHang()) != 0) {
                JOptionPane.showMessageDialog(this, "Huy thanh cong");
                fillToTable();
            } else {

                JOptionPane.showMessageDialog(this, "Huy khong thanh cong");

            }
        }
    }

    public void showDetail() {
        index = tblDonhang.getSelectedRow();
        DonHang dh = listDH.get(index);
        int giaTri = dh.getMaDonHang();
        String giaTriText = String.valueOf(giaTri);
        txtMadonhang.setText(giaTriText);

    }

    public void updateDH() {
        DonHangDao dhdao = new DonHangDao();
        index = tblDonhang.getSelectedRow();
        DonHang dh = listDH.get(index);

        dh.setMaDonHang(Integer.parseInt(txtMadonhang.getText()));
        String trangthai = (String) cboTrangThai.getSelectedItem();
        dh.setTrangThai(trangthai);

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Hay chon Phieu nhap muon update");

        } else {
            if (dhdao.updateDonHang(dh) > 0) {
                fillToTable();
                JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "Cap nhat that bai");
            }
        }
    }

    public void showCTDH() {
        fadd.setMaDonHang(Integer.parseInt(txtMadonhang.getText()));
        fadd.fillToTable();
        fadd.loadForm(this);
        fadd.setVisible(true);

    }

    public void tongSL() {
        int kq = dhDao.tongSL();
        if (kq != 0) {
            lblTongSL.setText("Tổng số lượng : " + kq);
        } else {
            lblTongSL.setText("Tổng số lượng : " + 0);
        }
    }
}
