/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.PhieuNhapDao;
import MODEL.PhieuNhap;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranh
 */
public class frmPhieuNhap extends javax.swing.JInternalFrame {

    List<PhieuNhap> listPN = new ArrayList<>();
    PhieuNhapDao pnDao = new PhieuNhapDao();
    PhieuNhap pn = new PhieuNhap();

    int index = 0;
    DefaultTableModel tblModel = new DefaultTableModel();

    public frmPhieuNhap() {
        initComponents();
        fillToTable();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
//         Date date = new Date();
//            SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//            String ngayHienTai = formatter.format(date);
//            txtNgaynhap.setText(ngayHienTai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnXuatDS = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblTongSL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieunhap = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1650, 855));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnXuatDS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXuatDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnXuatDS.setText("Xuất DS");
        btnXuatDS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnXuatDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDSActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset.setActionCommand("  Xóa");
        btnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setName(""); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lblTongSL.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTongSL.setForeground(new java.awt.Color(204, 0, 0));
        lblTongSL.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1045, Short.MAX_VALUE)
                .addComponent(lblTongSL)
                .addGap(54, 54, 54)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTongSL)))
                .addGap(28, 28, 28))
        );

        tblPhieunhap.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblPhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Ngày nhập", "Tổng giá trị", "Hình thức thanh toán", "Ghi chú"
            }
        ));
        tblPhieunhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPhieunhap.setRowHeight(50);
        tblPhieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieunhap);
        if (tblPhieunhap.getColumnModel().getColumnCount() > 0) {
            tblPhieunhap.getColumnModel().getColumn(0).setMinWidth(100);
            tblPhieunhap.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblPhieunhap.getColumnModel().getColumn(0).setMaxWidth(100);
            tblPhieunhap.getColumnModel().getColumn(1).setMinWidth(250);
            tblPhieunhap.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblPhieunhap.getColumnModel().getColumn(1).setMaxWidth(250);
            tblPhieunhap.getColumnModel().getColumn(2).setMinWidth(250);
            tblPhieunhap.getColumnModel().getColumn(2).setPreferredWidth(250);
            tblPhieunhap.getColumnModel().getColumn(2).setMaxWidth(250);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSActionPerformed

    }//GEN-LAST:event_btnXuatDSActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        fillToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        frmAddPhieuNhap fadd = new frmAddPhieuNhap();
        fadd.loadForm(this);

        fadd.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblPhieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieunhapMouseClicked

        showForm(index);
    }//GEN-LAST:event_tblPhieunhapMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXuatDS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongSL;
    private javax.swing.JTable tblPhieunhap;
    // End of variables declaration//GEN-END:variables
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    Date date = new Date();

    public void fillToTable() {
        listPN = pnDao.getlistPhieuNhap();
        tblModel = (DefaultTableModel) tblPhieunhap.getModel();
        tblModel.setRowCount(0);

        for (PhieuNhap sp : listPN) {
            String ngayNhap = sdf.format(sp.getNgayNhap());

            Object[] row = new Object[]{sp.getMaPhieuNhap(), ngayNhap, sp.getTongGiaTri(), sp.getHinhThucThanhToan(), sp.getGhiChu()};
            tblModel.addRow(row);
        }
        tblPhieunhap.setModel(tblModel);
        tongSL();
    }

    public void showForm(int index) {

        int selectedRow = tblPhieunhap.getSelectedRow();
        if (selectedRow != -1) {

            String mapn = tblPhieunhap.getValueAt(selectedRow, 0).toString();
            String ngaynhap = tblPhieunhap.getValueAt(selectedRow, 1).toString();
            String tongtien = tblPhieunhap.getValueAt(selectedRow, 2).toString();
            String httt = tblPhieunhap.getValueAt(selectedRow, 3).toString();
            String ghichu = tblPhieunhap.getValueAt(selectedRow, 4).toString();

            frmTuyChinhPN ctpn = new frmTuyChinhPN();
            ctpn.setVisible(true);
            ctpn.loadForm(this);
            ctpn.setData(mapn, ngaynhap, tongtien, httt, ghichu);
        }

    }

    public void tongSL() {
        int kq = pnDao.tongSL();
        if (kq != 0) {
            lblTongSL.setText("Tổng số lượng: " + kq);
        } else {
            lblTongSL.setText("" + 0);
        }
    }
}
