
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.SanPhamDao;
import MODEL.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranh
 */
public class frmSanPham extends javax.swing.JInternalFrame {

    List<SanPham> listSP = new ArrayList<>();
    SanPhamDao spDao = new SanPhamDao();
    SanPham sp = new SanPham();

    int index = 0;
    DefaultTableModel tblModel = new DefaultTableModel();

    public frmSanPham() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        fillToTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnXuatDS = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblTongSL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1650, 855));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnXuatDS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXuatDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnXuatDS.setText("Xuất DS");
        btnXuatDS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnXuatDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDSActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset.setActionCommand("  Xóa");
        btnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setName(""); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lblTongSL.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTongSL.setForeground(new java.awt.Color(204, 0, 0));
        lblTongSL.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongSL)
                .addGap(103, 103, 103)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTongSL)))
                .addGap(28, 28, 28))
        );

        tblSanPham.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá tiền", "Mô tả", "Ảnh bìa", "Mã loại", "Mã NSX", "Sản phẩm tồn", "Sản phẩm đã bán"
            }
        ));
        tblSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblSanPham.setRowHeight(50);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(0).setMinWidth(150);
            tblSanPham.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblSanPham.getColumnModel().getColumn(0).setMaxWidth(150);
            tblSanPham.getColumnModel().getColumn(1).setMinWidth(400);
            tblSanPham.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblSanPham.getColumnModel().getColumn(1).setMaxWidth(400);
            tblSanPham.getColumnModel().getColumn(2).setMinWidth(150);
            tblSanPham.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblSanPham.getColumnModel().getColumn(2).setMaxWidth(150);
            tblSanPham.getColumnModel().getColumn(3).setMinWidth(250);
            tblSanPham.getColumnModel().getColumn(3).setPreferredWidth(250);
            tblSanPham.getColumnModel().getColumn(3).setMaxWidth(250);
            tblSanPham.getColumnModel().getColumn(4).setMinWidth(250);
            tblSanPham.getColumnModel().getColumn(4).setPreferredWidth(250);
            tblSanPham.getColumnModel().getColumn(4).setMaxWidth(250);
            tblSanPham.getColumnModel().getColumn(5).setMinWidth(100);
            tblSanPham.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblSanPham.getColumnModel().getColumn(5).setMaxWidth(100);
            tblSanPham.getColumnModel().getColumn(6).setMinWidth(100);
            tblSanPham.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblSanPham.getColumnModel().getColumn(6).setMaxWidth(100);
            tblSanPham.getColumnModel().getColumn(7).setMinWidth(100);
            tblSanPham.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblSanPham.getColumnModel().getColumn(7).setMaxWidth(100);
            tblSanPham.getColumnModel().getColumn(8).setMinWidth(150);
            tblSanPham.getColumnModel().getColumn(8).setPreferredWidth(150);
            tblSanPham.getColumnModel().getColumn(8).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1634, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSActionPerformed

    }//GEN-LAST:event_btnXuatDSActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked

        showForm(index);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        frmAddSanPham fadd = new frmAddSanPham();
        fadd.setVisible(true);
        fadd.loadForm(this);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        fillToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXuatDS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongSL;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables

    private frmMain frmMainRef; // Tham chiếu của frmMain

    public frmSanPham(frmMain frmMainRef) {
        this.frmMainRef = frmMainRef;
    }

    public void fillToTable() {

        listSP = spDao.showAllSP();

        tblModel = (DefaultTableModel) tblSanPham.getModel();
        tblModel.setRowCount(0);
        for (SanPham sp : listSP) {
            Object[] row = new Object[]{sp.getMaSanPham(), sp.getTenSanPham(), sp.getGia(), sp.getMoTa(), sp.getAnh(), sp.getMaLoai(), sp.getMaNhaSanXuat(), sp.getSanPhamTon(), sp.getSanPhamDaBan()};
            tblModel.addRow(row);
        }
        tblSanPham.setModel(tblModel);
        tongSL();
    }

    public void showForm(int index) {

        int selectedRow = tblSanPham.getSelectedRow();
        if (selectedRow != -1) {

            String maSanPham = tblSanPham.getValueAt(selectedRow, 0).toString();
            String tenSanPham = tblSanPham.getValueAt(selectedRow, 1).toString();
            String giaTien = tblSanPham.getValueAt(selectedRow, 2).toString();
            String moTa = tblSanPham.getValueAt(selectedRow, 3).toString();
            String anh = tblSanPham.getValueAt(selectedRow, 4).toString();
            String maLoai = tblSanPham.getValueAt(selectedRow, 5).toString();
            String maNSX = tblSanPham.getValueAt(selectedRow, 6).toString();
            String spt = tblSanPham.getValueAt(selectedRow, 7).toString();
            String spdb = tblSanPham.getValueAt(selectedRow, 8).toString();

            frmTuyChinhSP ctsp = new frmTuyChinhSP();
            ctsp.setAnh(anh);
            ctsp.setVisible(true);
            ctsp.loadForm(this);
            ctsp.setData(maSanPham, tenSanPham, giaTien, moTa, anh, maLoai, maNSX, spt, spdb);
        }

    }

    public void tongSL() {
        int kq = spDao.tongSL();
        if (kq != 0) {
            lblTongSL.setText("Tổng số lượng sản phẩm: " + kq);
        } else {
            lblTongSL.setText("Tổng số lượng sản phẩm: " + 0);
        }
    }

}
