/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.TaiKhoanDao;
import MODEL.TaiKhoan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranh
 */
public class frmTaiKhoan extends javax.swing.JInternalFrame {

    List<TaiKhoan> listTK = new ArrayList<>();
    TaiKhoanDao tkDao = new TaiKhoanDao();
    TaiKhoan tk = new TaiKhoan();

    int index = 0;
    DefaultTableModel tblModel = new DefaultTableModel();

    public frmTaiKhoan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXuatDS = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1650, 855));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXuatDS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXuatDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnXuatDS.setText("Xuất DS");
        btnXuatDS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnXuatDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDSActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset.setActionCommand("  Xóa");
        btnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setName(""); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        tblTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vai trò", "Email", "Họ tên", "Ngày sinh", "Giới tính", "Số điện thoại", "Tên đăng nhập", "Mật khẩu", "Ảnh bìa"
            }
        ));
        tblTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTaiKhoan.setRowHeight(50);
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);
        if (tblTaiKhoan.getColumnModel().getColumnCount() > 0) {
            tblTaiKhoan.getColumnModel().getColumn(0).setMinWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(0).setMaxWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(3).setMinWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(3).setMaxWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(4).setMinWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(4).setMaxWidth(100);
            tblTaiKhoan.getColumnModel().getColumn(5).setMinWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(5).setMaxWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(8).setMinWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(8).setPreferredWidth(150);
            tblTaiKhoan.getColumnModel().getColumn(8).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1423, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSActionPerformed

    }//GEN-LAST:event_btnXuatDSActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        fillToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        frmAddTaiKhoan fadd = new frmAddTaiKhoan();
        fadd.loadForm(this);
        fadd.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked

        showForm(index);
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXuatDS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaiKhoan;
    // End of variables declaration//GEN-END:variables
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public void fillToTable() {

        listTK = tkDao.showAllTK();

        tblModel = (DefaultTableModel) tblTaiKhoan.getModel();
        tblModel.setRowCount(0);
        for (TaiKhoan sp : listTK) {
            String ngaySinhStr = sdf.format(sp.getNgaySinh());
            Object[] row = new Object[]{sp.getVaiTro(), sp.getEmail(), sp.getHoTen(), ngaySinhStr, sp.getGioiTinh(), sp.getSoDienThoai(), sp.getTenDN(), sp.getMatKhau(), sp.getAnhBiaUser()};
            tblModel.addRow(row);
        }
        tblTaiKhoan.setModel(tblModel);
    }

    public void showForm(int index) {

        int selectedRow = tblTaiKhoan.getSelectedRow();
        if (selectedRow != -1) {

            String vaitro = tblTaiKhoan.getValueAt(selectedRow, 0).toString();
            String email = tblTaiKhoan.getValueAt(selectedRow, 1).toString();
            String hoten = tblTaiKhoan.getValueAt(selectedRow, 2).toString();
            String ngaysinh = tblTaiKhoan.getValueAt(selectedRow, 3).toString();
            Date ngaySinhDate = null;
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                ngaySinhDate = dateFormat.parse(ngaysinh);
            } catch (Exception e) {
                e.printStackTrace();
            }
            String gioitinh = tblTaiKhoan.getValueAt(selectedRow, 4).toString();
            String sodienthoai = tblTaiKhoan.getValueAt(selectedRow, 5).toString();
            String tendn = tblTaiKhoan.getValueAt(selectedRow, 6).toString();
            String matkhau = tblTaiKhoan.getValueAt(selectedRow, 7).toString();
            String anh = tblTaiKhoan.getValueAt(selectedRow, 8).toString();

            frmTuyChinhTK ctsp = new frmTuyChinhTK();
            ctsp.setVisible(true);
            ctsp.loadForm(this);
            ctsp.setData(vaitro, email, hoten, ngaySinhDate, gioitinh, sodienthoai, tendn, matkhau, anh);
        }

    }
}
